export const archetypes = {
  de: [
    { id: "der-unschuldige", name: "Der Unschuldige", tagline: "Das Leben kann einfach sein", description: "Der Unschuldige strebt nach Glück und Harmonie. Er glaubt an das Gute und möchte, dass die Welt ein besserer Ort wird.", traits: ["Optimistisch", "Ehrlich", "Einfach", "Rein", "Vertrauensvoll"], brands: ["Dove", "Coca-Cola", "Innocent"], motivation: "Glück finden & Gutes tun" },
    { id: "der-entdecker", name: "Der Entdecker", tagline: "Grenzen existieren nur im Kopf", description: "Der Entdecker sucht Freiheit und Abenteuer. Er bricht aus dem Alltag aus und entdeckt Neues.", traits: ["Unabhängig", "Mutig", "Neugierig", "Abenteuerlich", "Authentisch"], brands: ["Patagonia", "The North Face", "Jeep"], motivation: "Die Welt entdecken & Freiheit erleben" },
    { id: "der-weise", name: "Der Weise", tagline: "Wissen ist der Weg zur Wahrheit", description: "Der Weise sucht nach Erkenntnis und Wahrheit. Er analysiert, versteht und teilt sein Wissen.", traits: ["Intelligent", "Analytisch", "Objektiv", "Kompetent", "Wissend"], brands: ["Google", "BBC", "TED"], motivation: "Wahrheit finden & Wissen teilen" },
    { id: "der-held", name: "Der Held", tagline: "Wo ein Wille ist, ist ein Weg", description: "Der Held will die Welt verbessern durch Mut und Entschlossenheit. Er stellt sich Herausforderungen und inspiriert andere.", traits: ["Mutig", "Entschlossen", "Stark", "Diszipliniert", "Inspirierend"], brands: ["Nike", "Adidas", "FedEx"], motivation: "Herausforderungen meistern & Großes erreichen" },
    { id: "der-rebell", name: "Der Rebell", tagline: "Regeln sind dazu da, gebrochen zu werden", description: "Der Rebell stellt den Status quo in Frage. Er bricht mit Konventionen und schafft radikal Neues.", traits: ["Rebellisch", "Provokant", "Disruptiv", "Unkonventionell", "Frei"], brands: ["Harley-Davidson", "Diesel", "Virgin"], motivation: "Veränderung bewirken & Konventionen brechen" },
    { id: "der-magier", name: "Der Magier", tagline: "Alles ist möglich", description: "Der Magier verwandelt Visionen in Realität. Er macht das Unmögliche möglich und schafft transformative Erlebnisse.", traits: ["Visionär", "Innovativ", "Charismatisch", "Transformativ", "Inspirierend"], brands: ["Apple", "Tesla", "Disney"], motivation: "Träume verwirklichen & Transformation schaffen" },
    { id: "der-jedermann", name: "Der Jedermann", tagline: "Alle Menschen sind gleich", description: "Der Jedermann möchte dazugehören und verbindet Menschen. Er ist bodenständig und verlässlich.", traits: ["Bodenständig", "Verlässlich", "Zugänglich", "Ehrlich", "Verbindend"], brands: ["IKEA", "Volkswagen", "eBay"], motivation: "Zugehörigkeit schaffen & verbinden" },
    { id: "der-liebende", name: "Der Liebende", tagline: "Du bist es wert", description: "Der Liebende steht für Leidenschaft und Sinnlichkeit. Er schafft emotionale Verbindungen und ästhetische Erlebnisse.", traits: ["Leidenschaftlich", "Sinnlich", "Ästhetisch", "Elegant", "Wertschätzend"], brands: ["Chanel", "Victoria's Secret", "Häagen-Dazs"], motivation: "Schönheit schaffen & Liebe ausdrücken" },
    { id: "der-narr", name: "Der Narr", tagline: "Man lebt nur einmal", description: "Der Narr bringt Freude und Leichtigkeit in die Welt. Er nimmt sich selbst nicht zu ernst.", traits: ["Humorvoll", "Spontan", "Kreativ", "Verspielt", "Unbeschwert"], brands: ["Old Spice", "M&M's", "Ben & Jerry's"], motivation: "Freude verbreiten & den Moment genießen" },
    { id: "der-betreuer", name: "Der Betreuer", tagline: "Liebe Deinen Nächsten wie Dich selbst", description: "Der Betreuer kümmert sich um andere. Er ist fürsorglich, beschützend und großzügig.", traits: ["Fürsorglich", "Großzügig", "Beschützend", "Mitfühlend", "Verlässlich"], brands: ["UNICEF", "Volvo", "Johnson & Johnson"], motivation: "Andere schützen & Gutes tun" },
    { id: "der-schoepfer", name: "Der Schöpfer", tagline: "Wenn Du es Dir vorstellen kannst, kannst Du es schaffen", description: "Der Schöpfer verwirklicht Ideen und schafft bleibende Werke. Er ist kreativ und hat eine einzigartige Vision.", traits: ["Kreativ", "Originell", "Visionär", "Ausdrucksstark", "Perfektionistisch"], brands: ["Lego", "Adobe", "Moleskine"], motivation: "Neues erschaffen & Vision verwirklichen" },
    { id: "der-herrscher", name: "Der Herrscher", tagline: "Macht ist nicht alles — sie ist das Einzige", description: "Der Herrscher übernimmt Verantwortung und schafft Ordnung. Er steht für Führung, Stabilität und Premium-Qualität.", traits: ["Führungsstark", "Kontrolliert", "Premium", "Verantwortungsvoll", "Stabil"], brands: ["Mercedes-Benz", "Rolex", "Microsoft"], motivation: "Kontrolle übernehmen & Ordnung schaffen" },
  ],
  en: [
    { id: "the-innocent", name: "The Innocent", tagline: "Life can be simple", description: "The Innocent strives for happiness and harmony. They believe in goodness and want to make the world a better place.", traits: ["Optimistic", "Honest", "Simple", "Pure", "Trustful"], brands: ["Dove", "Coca-Cola", "Innocent"], motivation: "Find happiness & do good" },
    { id: "the-explorer", name: "The Explorer", tagline: "Boundaries only exist in the mind", description: "The Explorer seeks freedom and adventure. They break free from the everyday and discover new things.", traits: ["Independent", "Brave", "Curious", "Adventurous", "Authentic"], brands: ["Patagonia", "The North Face", "Jeep"], motivation: "Discover the world & experience freedom" },
    { id: "the-sage", name: "The Sage", tagline: "Knowledge is the path to truth", description: "The Sage seeks knowledge and truth. They analyze, understand, and share their wisdom.", traits: ["Intelligent", "Analytical", "Objective", "Competent", "Knowledgeable"], brands: ["Google", "BBC", "TED"], motivation: "Find truth & share knowledge" },
    { id: "the-hero", name: "The Hero", tagline: "Where there's a will, there's a way", description: "The Hero wants to improve the world through courage and determination.", traits: ["Courageous", "Determined", "Strong", "Disciplined", "Inspiring"], brands: ["Nike", "Adidas", "FedEx"], motivation: "Master challenges & achieve greatness" },
    { id: "the-rebel", name: "The Rebel", tagline: "Rules are made to be broken", description: "The Rebel questions the status quo. They break conventions and create radical change.", traits: ["Rebellious", "Provocative", "Disruptive", "Unconventional", "Free"], brands: ["Harley-Davidson", "Diesel", "Virgin"], motivation: "Drive change & break conventions" },
    { id: "the-magician", name: "The Magician", tagline: "Anything is possible", description: "The Magician turns visions into reality and creates transformative experiences.", traits: ["Visionary", "Innovative", "Charismatic", "Transformative", "Inspiring"], brands: ["Apple", "Tesla", "Disney"], motivation: "Make dreams real & create transformation" },
    { id: "the-everyman", name: "The Everyman", tagline: "All people are equal", description: "The Everyman wants to belong and connect people. They are down-to-earth and dependable.", traits: ["Down-to-earth", "Reliable", "Accessible", "Honest", "Connecting"], brands: ["IKEA", "Volkswagen", "eBay"], motivation: "Create belonging & connect people" },
    { id: "the-lover", name: "The Lover", tagline: "You are worth it", description: "The Lover stands for passion and sensuality. They create emotional connections and aesthetic experiences.", traits: ["Passionate", "Sensual", "Aesthetic", "Elegant", "Appreciative"], brands: ["Chanel", "Victoria's Secret", "Häagen-Dazs"], motivation: "Create beauty & express love" },
    { id: "the-jester", name: "The Jester", tagline: "You only live once", description: "The Jester brings joy and lightness to the world and breaks barriers through humor.", traits: ["Humorous", "Spontaneous", "Creative", "Playful", "Carefree"], brands: ["Old Spice", "M&M's", "Ben & Jerry's"], motivation: "Spread joy & enjoy the moment" },
    { id: "the-caregiver", name: "The Caregiver", tagline: "Love thy neighbor as thyself", description: "The Caregiver takes care of others. They are nurturing, protective, and generous.", traits: ["Caring", "Generous", "Protective", "Compassionate", "Reliable"], brands: ["UNICEF", "Volvo", "Johnson & Johnson"], motivation: "Protect others & do good" },
    { id: "the-creator", name: "The Creator", tagline: "If you can imagine it, you can create it", description: "The Creator realizes ideas and builds lasting works with a unique vision.", traits: ["Creative", "Original", "Visionary", "Expressive", "Perfectionist"], brands: ["Lego", "Adobe", "Moleskine"], motivation: "Create something new & realize vision" },
    { id: "the-ruler", name: "The Ruler", tagline: "Power isn't everything — it's the only thing", description: "The Ruler takes responsibility and creates order. They stand for leadership and premium quality.", traits: ["Leading", "Controlled", "Premium", "Responsible", "Stable"], brands: ["Mercedes-Benz", "Rolex", "Microsoft"], motivation: "Take control & create order" },
  ],
}

export const archetypeIcons = {
  "der-unschuldige": "🕊️", "the-innocent": "🕊️",
  "der-entdecker": "🧭", "the-explorer": "🧭",
  "der-weise": "📚", "the-sage": "📚",
  "der-held": "⚔️", "the-hero": "⚔️",
  "der-rebell": "🔥", "the-rebel": "🔥",
  "der-magier": "✨", "the-magician": "✨",
  "der-jedermann": "🤝", "the-everyman": "🤝",
  "der-liebende": "❤️", "the-lover": "❤️",
  "der-narr": "🎭", "the-jester": "🎭",
  "der-betreuer": "🛡️", "the-caregiver": "🛡️",
  "der-schoepfer": "🎨", "the-creator": "🎨",
  "der-herrscher": "👑", "the-ruler": "👑",
}

export const questions = [
  {
    id: "intro",
    key: "intro",
    section: "intro",
    sectionNumber: "00",
    theme: "lime",
    title: { de: "Brand Strategy Questionnaire", en: "Brand Strategy Questionnaire" },
    description: { de: "Dieser Fragebogen hilft uns, Eure Marke zu verstehen. Nehmt Euch Zeit — es gibt keine falschen Antworten.", en: "This questionnaire helps us understand your brand. Take your time — there are no wrong answers." },
    fields: [
      { key: "clientName", type: "input", label: { de: "Euer Name / Firma", en: "Your name / company" }, placeholder: { de: "z.B. Max Mustermann, Firma GmbH", en: "e.g. John Smith, Company Inc." } },
      { key: "clientEmail", type: "input", label: { de: "E-Mail", en: "Email" }, placeholder: { de: "email@beispiel.de", en: "email@example.com" } },
    ],
  },
  {
    id: "projektbeschreibung",
    key: "projektbeschreibung",
    section: "part1",
    sectionNumber: "01",
    theme: "light",
    title: { de: "Worum geht's?", en: "What's it about?" },
    description: { de: "Beschreibt Euer Projekt in eigenen Worten.", en: "Describe your project in your own words." },
    fields: [{ key: "projektbeschreibung", type: "textarea", label: { de: "Projektbeschreibung", en: "Project Description" }, placeholder: { de: "Erzählt uns von Eurem Vorhaben...", en: "Tell us about your project..." } }],
  },
  {
    id: "hintergruende",
    key: "hintergruende",
    section: "part1",
    sectionNumber: "01",
    theme: "light",
    title: { de: "Hintergründe", en: "Background" },
    description: { de: "Wie kommt es zu diesem Projekt? Warum jetzt?", en: "How did this project come about? Why now?" },
    fields: [{ key: "hintergruende", type: "textarea", label: { de: "Hintergründe", en: "Background" }, placeholder: { de: "Was ist der Anlass oder Auslöser?", en: "What is the trigger or reason?" } }],
  },
  {
    id: "zielgruppen",
    key: "zielgruppen",
    section: "part1",
    sectionNumber: "01",
    theme: "light",
    title: { de: "Zielgruppen", en: "Target Audiences" },
    description: { de: "Für wen wird das Projekt umgesetzt? Und wer ist das?", en: "Who is the project being created for?" },
    fields: [{ key: "zielgruppen", type: "textarea", label: { de: "Zielgruppen", en: "Target Audiences" }, placeholder: { de: "Beschreibt Eure Zielgruppe(n)...", en: "Describe your target audience(s)..." } }],
  },
  {
    id: "zeitraum",
    key: "zeitraum",
    section: "part1",
    sectionNumber: "01",
    theme: "light",
    title: { de: "Zeitraum", en: "Timeline" },
    description: { de: "Gibt es einen Zeitplan oder feste Milestones?", en: "Is there a timeline or fixed milestones?" },
    fields: [{ key: "zeitraum", type: "textarea", label: { de: "Zeitraum", en: "Timeline" }, placeholder: { de: "Wichtige Termine und Deadlines...", en: "Key dates and deadlines..." } }],
  },
  {
    id: "vorhandenesMaterial",
    key: "vorhandenesMaterial",
    section: "part1",
    sectionNumber: "01",
    theme: "light",
    title: { de: "Vorhandenes Material", en: "Existing Material" },
    description: { de: "Was gibt es bereits (z.B. Studien, Umfragen, Strategiepapiere, erste Designs, Prototypen etc.)?", en: "What already exists (e.g. studies, surveys, strategy papers, initial designs, prototypes)?" },
    fields: [{ key: "vorhandenesMaterial", type: "textarea", label: { de: "Material", en: "Material" }, placeholder: { de: "Was existiert bereits?", en: "What already exists?" } }],
  },
  {
    id: "ziele",
    key: "ziele",
    section: "part1",
    sectionNumber: "01",
    theme: "light",
    title: { de: "Ziele", en: "Goals" },
    description: { de: "Was soll erreicht werden (z.B. Projekt- oder Unternehmensziele)?", en: "What should be achieved (e.g. project or company goals)?" },
    fields: [{ key: "ziele", type: "textarea", label: { de: "Ziele", en: "Goals" }, placeholder: { de: "Was wollt Ihr erreichen?", en: "What do you want to achieve?" } }],
  },
  {
    id: "wettbewerb",
    key: "wettbewerb",
    section: "part1",
    sectionNumber: "01",
    theme: "light",
    title: { de: "Wettbewerb", en: "Competition" },
    description: { de: "Wer sind die wichtigsten Wettbewerber?", en: "Who are the most important competitors?" },
    fields: [{ key: "wettbewerb", type: "textarea", label: { de: "Wettbewerber", en: "Competitors" }, placeholder: { de: "Listet Eure Wettbewerber auf...", en: "List your competitors..." } }],
  },
  {
    id: "timeline",
    key: "timeline",
    section: "part2",
    sectionNumber: "02",
    theme: "dark",
    title: { de: "Markenvision", en: "Brand Vision" },
    description: { de: "Was hat Eure Marke in 2, 5 und 10 Jahren erreicht?", en: "What has your brand achieved in 2, 5, and 10 years?" },
    fields: [
      { key: "timeline2years", type: "textarea", label: { de: "In 2 Jahren", en: "In 2 years" }, placeholder: { de: "Was habt Ihr in 2 Jahren erreicht?", en: "What have you achieved in 2 years?" } },
      { key: "timeline5years", type: "textarea", label: { de: "In 5 Jahren", en: "In 5 years" }, placeholder: { de: "Was habt Ihr in 5 Jahren erreicht?", en: "What have you achieved in 5 years?" } },
      { key: "timeline10years", type: "textarea", label: { de: "In 10 Jahren", en: "In 10 years" }, placeholder: { de: "Was habt Ihr in 10 Jahren erreicht?", en: "What have you achieved in 10 years?" } },
    ],
  },
  {
    id: "goldenCircle",
    key: "goldenCircle",
    section: "part2",
    sectionNumber: "02",
    theme: "dark",
    title: { de: "Golden Circle", en: "Golden Circle" },
    description: { de: "Simon Sinek's Golden Circle — Why, How, What.", en: "Simon Sinek's Golden Circle — Why, How, What." },
    fields: [
      { key: "goldenCircleWhy", type: "textarea", label: { de: "Why / Purpose — Warum gibt es Euch?", en: "Why / Purpose — Why do you exist?" }, placeholder: { de: "Was ist Euer tieferer Antrieb?", en: "What is your deeper motivation?" } },
      { key: "goldenCircleHow", type: "textarea", label: { de: "How — Wie setzt Ihr das um?", en: "How — How do you do it?" }, placeholder: { de: "Was macht Euch besonders?", en: "What makes you special?" } },
      { key: "goldenCircleWhat", type: "textarea", label: { de: "What / Angebot — Was bietet Ihr an?", en: "What / Offering — What do you offer?" }, placeholder: { de: "Eure Produkte und Services...", en: "Your products and services..." } },
    ],
  },
  {
    id: "markenwerte",
    key: "markenwerte",
    section: "part2",
    sectionNumber: "02",
    theme: "dark",
    title: { de: "Markenwerte", en: "Brand Values" },
    description: { de: "Mit welchen Werten soll Eure Marke in Verbindung gebracht werden? Wählt max. 3 Kernwerte und max. 5 unterstützende Werte.", en: "What values should your brand be associated with? Choose max 3 core values and max 5 supporting values." },
    fields: [{ key: "markenwerte", type: "values-pyramid", label: { de: "Markenwerte", en: "Brand Values" } }],
  },
  {
    id: "markenpersoenlichkeit",
    key: "markenpersoenlichkeit",
    section: "part2",
    sectionNumber: "02",
    theme: "lime",
    title: { de: "Markenpersönlichkeit", en: "Brand Personality" },
    description: { de: "Stellt Euch vor, Eure Marke wäre eine Person. Wie würdet Ihr sie beschreiben?", en: "Imagine your brand as a person. How would you describe them?" },
    fields: [{ key: "markenpersoenlichkeit", type: "textarea", label: { de: "Markenpersönlichkeit", en: "Brand Personality" }, placeholder: { de: "Beschreibt die Persönlichkeit Eurer Marke...", en: "Describe your brand's personality..." } }],
  },
  {
    id: "brandArchetype",
    key: "brandArchetype",
    section: "part2",
    sectionNumber: "02",
    theme: "light",
    title: { de: "Brand Archetype", en: "Brand Archetype" },
    description: { de: "Welchem Archetypen entspricht Eure Marke am besten?", en: "Which archetype best fits your brand?" },
    fields: [{ key: "brandArchetype", type: "archetype", label: { de: "Archetyp", en: "Archetype" } }],
  },
  {
    id: "elevatorPitch",
    key: "elevatorPitch",
    section: "part2",
    sectionNumber: "02",
    theme: "light",
    title: { de: "Elevator Pitch", en: "Elevator Pitch" },
    description: { de: "Fasst Eure Marke in einem Satz zusammen. Was ist Eure Value Proposition?", en: "Summarize your brand in one sentence. What is your value proposition?" },
    fields: [{ key: "elevatorPitch", type: "textarea", label: { de: "Elevator Pitch", en: "Elevator Pitch" }, placeholder: { de: "In einem Satz...", en: "In one sentence..." } }],
  },
  {
    id: "benchmarks",
    key: "benchmarks",
    section: "benchmarks",
    sectionNumber: "03",
    theme: "lime",
    title: { de: "Benchmarks", en: "Benchmarks" },
    description: { de: "Welche Marken sind Benchmarks für Euch in Bezug auf Design? Welche Webseiten gefallen Euch?", en: "Which brands are benchmarks for you in terms of design? Which websites do you like?" },
    fields: [{ key: "benchmarks", type: "textarea", label: { de: "Benchmarks", en: "Benchmarks" }, placeholder: { de: "Links, Markennamen, Beschreibungen...", en: "Links, brand names, descriptions..." } }],
  },
]

export const sectionLabels = {
  intro: { de: "Start", en: "Start" },
  part1: { de: "Teil 1 — Projekt & Kontext", en: "Part 1 — Project & Context" },
  part2: { de: "Teil 2 — Brand Sprint", en: "Part 2 — Brand Sprint" },
  benchmarks: { de: "Benchmarks", en: "Benchmarks" },
}

export const uiStrings = {
  next: { de: "Weiter", en: "Next" },
  back: { de: "Zurück", en: "Back" },
  start: { de: "Los geht's", en: "Let's go" },
  submit: { de: "Absenden", en: "Submit" },
  submitting: { de: "Wird gesendet...", en: "Submitting..." },
  questionOf: { de: "von", en: "of" },
  coreValues: { de: "Kernwerte (max. 3)", en: "Core Values (max. 3)" },
  supportValues: { de: "Unterstützende Werte (max. 5)", en: "Supporting Values (max. 5)" },
  enterValue: { de: "Wert eingeben...", en: "Enter value..." },
  selectArchetype: { de: "Auswählen", en: "Select" },
  selected: { de: "Ausgewählt ✓", en: "Selected ✓" },
  exampleBrands: { de: "Beispiel-Marken", en: "Example Brands" },
}
